LILAS/LILAS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('communication/', include('communication.urls')),
    path('configSalle/', include('configSalle.urls')),
    path('incident/', include('incident.urls')),
    path('loadFic/', include('loadFic.urls')),
    path('',include('loadFic.urls')),
    path('admin/', admin.site.urls),

]

LILAS/configSalle/urls.py
from django.urls import path

from . import views

app_name = 'configSalle'
urlpatterns = [
    path('', views.index, name='index'),
    # path('json/confs.json', views.loadjson, name='loadjson'),     # solution avortée du Json
]

LILAS/configSalle/models.py
from django.db import models
from django.utils import timezone


class ConfigurationSalle(models.Model):
    date = models.DateTimeField()   #Il faudrait faire un test dans le programme pour savoir si la valeur par défaut a été utilisée
    
    class Meta:
        ordering = ['date']
    
    def __str__(self):
        # return self.date.__str__() # Pour test affichage "conf" dans chrgt_conf_salle
        return self.date.__str__()

        
        
class Uce(models.Model):
    configurationSalle = models.ForeignKey(ConfigurationSalle, related_name='confUce', on_delete=models.CASCADE)   # related_name (par défaut: uce_set) permet de définir le nom à
    nomUce = models.CharField(max_length=30)                                                                       # utiliser pour la relation inverse depuis l’objet lié vers celui-ci.
    secteurs = models.CharField(max_length=300)
    
    class Meta:
        ordering = ['configurationSalle']
    
    def __str__(self):
        return '%s: %s' % (self.nomUce, self.secteurs)

LILAS/configSalle/forms.py
from django import forms
from django.contrib.admin import widgets

class DateForm(forms.Form):
    date = forms.DateField(label='dateForm', widget=widgets.AdminDateWidget())

LILAS/configSalle/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from configSalle.models import Uce, ConfigurationSalle
from .forms import DateForm

# from django.core import serializers       # solution avortée du Json
# from configSalle.models import ConfSerializer
# import json

from datetime import datetime
import pytz

def index(request):
    # uceListe = Uce.objects.all() #On récupère la liste de toutes les conf des uce
    
    #LISTE DE VARIABLES GLOBALES
    formulaireDates = DateForm(request.POST)
    #---------------------------
    context = {'form':formulaireDates}
    
    if request.method == 'POST': #Si on a rempli un formulaire /!\ Chercher comment différencier les différents formulaire d'une même page /!\
            
            if formulaireDates.is_valid(): #Si on a rempli le formulaire de choix de date / secteur / correspondant pour afficher les appels
                # process the data in form.cleaned_data as required
                print("FORMULAIRE DATE VALIDE")
<<<<<<< HEAD
=======
                uceListe = Uce.objects.all() #On récupère la liste de toutes les conf des uces
                confListe = ConfigurationSalle.objects.all() #On récupère la liste de toutes les configurationSalle effectuées
>>>>>>> 0d6bd3cc6aeb78b821e460c96b4f421b2c1910ea
                
                date = formulaireDates.cleaned_data['date'] #On récupère la dete de début entrée dans le formulaire
                
                #On crée ensuite les objets datetime de début et de fin
                date_time_deb = datetime( date.year, date.month, date.day, 00, 00, 00) #date naive
                date_time_fin = datetime( date.year, date.month, date.day, 23, 59, 00) #date naive aussi
                
                timzeone = pytz.timezone('UTC') #Définition de la zone horaire pour rendre la date aware
                date_time_deb_aware = timzeone.localize(date_time_deb) #Pour faire le test suivant, le fuseau horaire de la date associée doit être renseigné 'aware'
                date_time_fin_aware = timzeone.localize(date_time_fin)
                
                
<<<<<<< HEAD
                #On crée la liste d'uces à afficher et on l'initialise
                uces=[]
                if len(confs) !=0:
                    uces = confs[0].confUce.all()
                    for i in range(confs.count()) :
                        uces = uces | confs[i].confUce.all()  #cet opérateur combine les querysets entre eux
                
=======
>>>>>>> 0d6bd3cc6aeb78b821e460c96b4f421b2c1910ea
                #On change la variable contexte à envoyer au html
                #On crée la liste d'uces à afficher
                uces = []
                
                for i in uceListe :
                    if (i.configurationSalle.date > date_time_deb_aware) and (i.configurationSalle.date < date_time_fin_aware) : #Si la date de la conf sur l'uce est comprise entre les deux dates du formulaire
                            uces.append(i) #On ajoute l'uce à la fin de la liste
                
                
                #On crée la liste de confSalle à afficher
                confs = []
                dateSeconde = [] # Pour permettre un affichage des secondes < 10 sur 2 digits
                
                for i in confListe :
                    if (i.date > date_time_deb_aware) and (i.date < date_time_fin_aware) : #Si la date de la conf sur l'uce est comprise entre les deux dates du formulaire
                            confs.append(i) #On ajoute l'uce à la fin de la liste
                
                # data = serializers.serialize("json", uceListe)
                # with open("configSalle/data.json", 'a') as out:
                    # json.dump(data, indent=4, out)
                 
                # with open('configSalle/json/confs.json', 'w', encoding='utf-8') as f:
                    # f.write('[')
                    # for i in confs:
                        # # json.dump(i, f, indent=4, default=UceSerializer)
                        # confSerialize = ConfSerializer(i).data
                        # json.dump(confSerialize, f, indent=4)
                        # if confs.index(i) != len(confs)-1:
                            # f.write(',')
                    # f.write(']')
                    
                context = { 'uceListe':uces, 'confListe':confs, 'date':date, 'form':formulaireDates}
                
                # redirect to a new URL:
                return render(request, 'configSalle/index.html', context) #On recharge la pagee                
                
                
                
            #else :
                #Dans le cas où le formulaire n'est pas correct
                
                #Il faudrait ajouter un champ dans contexte qui contient une chaine de caractère du genre "Il est nécessaire de remplir tous les champs" 
                #puis de faire un test dans le html juste en dessous du formulaire tel que "Si ce champ de contexte existe, alors l'afficher,
                #sinon, ne pas l'afficher"
                
                #A ce moment là on a plus besoin de contexte juste avant "if form.is_valid():"

                #render(request, 'incident/index.html') #provisoire
                
    
    else :                  #Dans le cas où on a pas récupéré un POST 
        form = DateForm()   #On crée le formulaire à afficher
        bool = True         #Permet de différencier le cas où le 'form' n'a pas été renseigné et/ou n'ets pas valide
        context = {'bool':bool, 'form':form}
        
    return render(request, 'configSalle/index.html', context)

# def loadjson(request):
    # json_file = open("configSalle/json/confs.json", 'r')
    # json_content = json_file.read()
    # json_file.close()
    # return HttpResponse(
        # json_content,
        # content_type='application/json',
        # status=200   # status_code = OK
    # )

LILAS/configSalle/templates/configSalle/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'configSalle/style.css' %}">
        
       <!-- NECESSAIRE A L'AFFICHAGE DU DATEPICKER -->
        <link rel="stylesheet" href="{% static 'configSalle/lib_ext/datePicker.css' %}" />
       
        <title>LILAS</title>
    </head>
    <body>
        <header>
        <table style="width:100%;">
            <tr>
                <th> <h1>L I L A S</h1> </th>
                <th class="boutonApp" onclick="window.location.href='/incident'">Tickets d'événements</th> 
                <th class="boutonApp" onclick="window.location.href='/communication'">Tickets de communication</th>
                <th class="boutonApp" onclick="window.location.href='/configSalle'" style="border-bottom: 5px solid #d3defc;">Tickets opérateurs</th>
                <th class="boutonApp" onclick="window.location.href='/loadFic'"><img style="width: 30px; border-radius: 30px;" src="{% static 'loadFic/images/upload_icon.png' %}"></img></th>
            </tr>
        </table>
        </header>
        
            <table>
                <tr>
                    <form action="." method="post" autocomplete="off">
                        <th> 
                                {% csrf_token %}
                                <ul>
                                    <li>Sélectionner la date : {{ form.date }}</li>
                                </ul>
                                
                        </th>
                        <th> <input type="submit" value="Valider"> </th>
                    </form>
                </tr>
            </table>
        
       <div id = "alignMain">
        {% if not bool %}
        <div class = divConfUce>Configuration sélectionée : Aucune
            <table id ='tabConfSelect'></table>
           {% endif %}
        </div>
        <div id = "boutonMain">
        <div class = dateTabBouton>
           {% if date %}
                Configurations de la salle du : {{ date }}
           {% endif %}
        </div>
        <div class = uceBoutonConf >
               {% if uceListe %}
                    <table id = 'tableUceListe' hidden>
                        {% for Uce in uceListe %}
                            <tr>
                                <td>{{ Uce.configurationSalle.date|date:"d/m/y_H:i:s" }}</td>
                                <td>{{ Uce.nomUce }}</td>
                                <td>{{ Uce.secteurs }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                        <div  class = divBouton>
                    {% for ConfigurationSalle in confListe %} 
                            <button class = boutonConf id='boutonConf' conf="{{ ConfigurationSalle.date|date:'d/m/y_H:i:s' }}"><div>Conf_{{ ConfigurationSalle.date|date:"d/m/y" }}</div><div>{{ ConfigurationSalle.date|date:"H:i:s" }}</div></button>
                    {% endfor %}
                        </div>
                    
               {% elif bool %}
                   <p>Veuillez sélectionner une date.</p>
               {% else %}
                   <p><strong>Aucune configuration de salle répertoriée.</strong></p>
               {% endif %}
        </div>
        </div>
        </div>

        <footer>
        </footer>
        
        <script type="text/javascript">
        
// //------ Test avec un Json (trop complexe pour l'utilisation souhaitée + pb securisation serveur ------//
        
//         <!-- var uceName = '{{ uceListe.0.secteurs }}' -->
//         <!-- alert(uceName) -->
       
//         <!-- var requestURL = "http://127.0.0.1:8000/configSalle/json/confs.json";        -->
        
//         <!-- var request = new XMLHttpRequest(); -->
//         <!-- request.onreadystatechange = function() { -->
//             <!-- if (this.readyState == XMLHttpRequest.DONE && this.status == 200) { -->
//                 <!-- var response = JSON.parse(this.responseText); -->
//                 <!-- console.log(response.0.date); -->
//             <!-- } -->
//         <!-- }; -->
//         <!-- request.open("GET", requestURL); -->
//         <!-- request.send(); -->
         
// //------ Fin Test avec Json ------//



//------ Travail sur la solution de l'attribut hidden dans la balise ------//
        
            //On récupère le tableau de uceListe dans un tableau javascript
        if (document.getElementById("tableUceListe")!=null)
        {
            var tableau = document.getElementById("tableUceListe").rows;
            var longueur = tableau.length;
            var tabUceListe = new Array();
            
            console.log(tableau[0].cells[0].innerHTML); 
            
            for (var i = 0; i < longueur; i++)
            {
                var ligne = tableau[i].cells;
                var tampon = new Array();
                for (var j = 0; j < 3; j++)
                {
                    tampon.push(ligne[j].innerHTML);
                }
                tabUceListe.push(tampon);
            }
        }
            //tabUceListe est ici le tableau de conf des Uces. Il est rempli.
            
            
            //----- CLIQUE BOUTON CONF_DATE -----//
            
        var boutonConf = document.getElementsByClassName('boutonConf');     //on récupère l'élément du boutonConf
        var clickBoutonConf = function(){
            var attribut = this.getAttribute('conf');
            console.log("click bouton");
            
            // récupérer la référence du corps <div> qui nous intéresse          ref : https://developer.mozilla.org/fr/docs/Explorer_un_tableau_HTML_avec_des_interfaces_DOM_et_JavaScript
            // afin déviter qu'un nouveau tableau soit créé à chaque 'click'
            // on supprime le précédent
            var bodyParent = document.getElementsByTagName("div")[1];
            bodyParent.innerHTML = '<strong>Conf_'+attribut+'</strong><table id ="tabConfSelect"></table></div></div></div>';

            var bodyChild = document.getElementsByTagName("table")[2];
            // on supprime tout le contenu de l'élément en supprimant le bodyChild
            bodyParent.removeChild(bodyChild);
            bodyChild = document.createElement("table");
            bodyParent.appendChild(bodyChild);
            var body = document.getElementsByTagName("div")[1];
            
            // creation d'un elt <table>, cf. plus haut, d'un elt <thead> et d'un <tbody>
            //var bodyChild = document.createElement("table");
            var tblHead = document.createElement("thead");
            var tblBody = document.createElement("tbody");
            
            // on détermine le nombre de ligne que composera notre tableau avec l'attribut conf
            var tabConfOk = new Array();
            for (var i=0; i<longueur; i++){
                if ( tabUceListe[i][0] == attribut){
                    tabConfOk.push(tabUceListe[i]);
                }
            }
            var nbLignes=tabConfOk.length;
            /*console.log(nbLignes);
            console.log(tabConfOk[0]);*/
                        
            // on créé les cellules du tab dynamique
            // on initialise la première ligne du tab dynamique avec 'Uce :' et 'Secteur(s) affecté(s) :'
            var row = document.createElement("tr");
            var cell = document.createElement("th");
            var cellText = document.createTextNode("Uce(s) :");
            cell.appendChild(cellText);
            row.appendChild(cell);

            cell = document.createElement("th");
            cellText = document.createTextNode("Secteur(s) affecté(s) :");
            cell.appendChild(cellText);
            row.appendChild(cell);
            tblHead.appendChild(row);
            
            for (var i = 0; i < nbLignes; i++) {
            // création des lignes
                row = document.createElement("tr"); 

                for (var j = 0; j < 2; j++) {
                  // Create a <td> element and a text node, make the text
                  // node the contents of the <td>, and put the <td> at
                  // the end of the table row
                  cell = document.createElement("td");
                  cellText = document.createTextNode(tabConfOk[i][j+1]);
                  cell.appendChild(cellText);
                  row.appendChild(cell);
                }

            // add the row to the end of the table body
            tblBody.appendChild(row);
            }
            
            // on place le <thead> dans le <table>
            bodyChild.appendChild(tblHead);
            // put the <tbody> in the <table>
            bodyChild.appendChild(tblBody);
            // appends <table> into <div>
            body.appendChild(bodyChild);
            // sets the border attribute of bodyChild to 2;
            bodyChild.setAttribute("id","tabConfSelect");
        };
        
        Array.from(boutonConf).forEach(function(element){
            element.addEventListener('click', clickBoutonConf);
        });
       
        </script>
        
        
        
        <!-- NECESSAIRE A L'AFFICHAGE DU DATEPICKER -->
        <script src="{% static 'configSalle/lib_ext/datePicker_jquery-1.12.4.js' %}"></script>
        <script src="{% static 'configSalle/lib_ext/datePicker_jquery-ui.js' %}"></script>
        <script src="{% static 'configSalle/lib_ext/datePicker_jquery-ui.min.js' %}"></script>
    
        <!-- NECESSAIRE A L'AFFICHAGE DU DATEPICKER -->
        <script>
            $(document).ready(function(){
                $('#id_date').datepicker({ dateFormat: 'dd/mm/yy',
                changeMonth: true,
                changeYear: true,
                showWeek: true,
                firstDay: 1,
                /*showOtherMonths: true,
                selectOtherMonths: true*/ });
            });
        </script>
        
    </body>
    

</html>