LILAS/LILAS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('communication/', include('communication.urls')),
    path('configSalle/', include('configSalle.urls')),
    path('incident/', include('incident.urls')),
    path('loadFic/', include('loadFic.urls')),
    path('',include('loadFic.urls')),
    path('admin/', admin.site.urls),

]

LILAS/incident/urls.py
from django.urls import path

from . import views

app_name = 'incident'
urlpatterns = [
    path('', views.index, name='index'),
    #path('', views.IndexView.as_view(), name='index'),
]

LILAS/incident/models.py
from django.db import models

# Create your models here.

class Incident(models.Model):
    type_element = models.CharField(max_length=30) 
    nom_element = models.CharField(max_length=30) 
    etat_element = models.CharField(max_length=30) 
    gravite = models.CharField(max_length=30) 
    date_apparition = models.DateTimeField() 
    date_disparition_systeme = models.DateTimeField() 
    
    def __str__(self):
        return self.type_element+","+self.nom_element+","+self.etat_element+","+str(self.date_apparition)

LILAS/incident/forms.py
from django import forms
from django.contrib.admin import widgets

class DateForm(forms.Form):
    dateDebut = forms.DateField(label='Date de début : ', widget=widgets.AdminDateWidget())
    heureDebut  = forms.CharField(label='Heure de début (xx:xx:xx)', max_length=8)
    dateFin = forms.DateField(label='Date de fin : ',  widget=widgets.AdminDateWidget())
    heureFin = forms.CharField(label='Heure de Fin (xx:xx:xx)', max_length=8)

LILAS/incident/views.py
from django.shortcuts import render
from django.http import HttpResponse
from incident.models import Incident
from django.template import loader
from django.views import generic
from .forms import DateForm




from datetime import datetime
import pytz

def index(request):
    
    # IncidentListe = Incident.objects.all() #On récupère la liste de tous les Incidents --> PEUT POSER PROBLEME SI ON EN A 150 000
    
    if request.method == 'POST': #Si on a rempli le formulaire /!\ Chercher comment différencier les différents formulaire d'une même page /!\
        form = DateForm(request.POST)
        IncidentListe = Incident.objects.all()
        # context = {'IncidentListe':IncidentListe, 'form':form} 
        if form.is_valid():
            dateDeb = form.cleaned_data['dateDebut'] #On récupère la dete de début entrée dans le formulaire
            dateF = form.cleaned_data['dateFin'] #On récupère la dete de fin entrée dans le formulaire
            
            strHeureDebut = form.cleaned_data['heureDebut'] #On récupère l'heure de début sous forme de chaine de caractère (pour le moment)
            strHeureFin = form.cleaned_data['heureFin'] #On récupère l'heure de fin sous forme de chaine de caractère (pour le moment)
            
            # print(strHeureDebut)
            
            #On crée ensuite les objets datetime de début et de fin
            date_time_deb = datetime( dateDeb.year, dateDeb.month, dateDeb.day, int(strHeureDebut[0:2]),int(strHeureDebut[3:5]), int(strHeureDebut[6:8])) #date naive
            date_time_fin = datetime( dateF.year, dateF.month, dateF.day, int(strHeureFin[0:2]), int(strHeureFin[3:5]), int(strHeureFin[6:8])) #date naive aussi
            
            timzeone = pytz.timezone('UTC') #Définition de la zone horaire pour rendre la date aware
            date_time_deb_aware = timzeone.localize(date_time_deb)
            date_time_fin_aware = timzeone.localize(date_time_fin)
            
            #On change la variable contexte à envoyer au html
            
            liste=[] #liste contient tous les tickets d'incidents de la période séléctionnée
            
            for i in IncidentListe :
                if i.date_apparition > date_time_deb_aware and i.date_disparition_systeme < date_time_fin_aware :
                    liste.append(i)
            
                
            
            #On génère le tableau de statistiques
            #On commence par recenser tous les éléments tombés en panne (On ne met qu'une seule fois les éléments rombé en panne plusieurs fois)
            
            listeElement=[] #Liste qui contient tous les éléments tombés en panne
            listeStats=[] #Liste où sont tockées les statistiqyes (nombre d'occurrence et durée d'indisponnibilité)
            
            
            
            for element in liste :
                if(element.nom_element not in listeElement):
                    listeElement.append(element.nom_element)
                    listeStats.append([element.nom_element])
                  
                #element.nom_element figure forcement dans listeStats et listeElement
                #On récupère l'indice de listeStats auquel on a ajouté l'élément
                indice = listeElement.index(element.nom_element)
                
                #On ajoute 3 zéros au tableau listeStats[indice]
                for i in range(2):
                    listeStats[indice].append(0)
                
                #On incrémente le nombre d'occurrence 
                listeStats[indice][1] = listeStats[indice][1] + 1
                
                #On ajoute la durée d'indisponnibilité
                d1 = element.date_apparition
                d2 = element.date_disparition_systeme
                dur = d2-d1
                listeStats[indice][2] = listeStats[indice][2] + int(dur.total_seconds())
                   
            
            
            context = {'IncidentListe':liste, 'form':form, 'listeStats':listeStats} 
        
    else:
        form = DateForm(request.POST)
        # context = {'IncidentListe':IncidentListe, 'form':form} 
        context = {'form':form}
        
    return render(request, 'incident/index.html', context)
    
    

    def get_queryset(self):
        return 0

LILAS/incident/templates/incident/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'incident/style.css' %}">
        
       
       
       <!-- NECESSAIRE A L'AFFICHAGE DU DATEPICKER -->
        <link rel="stylesheet" href="{% static 'incident/lib_ext/datePicker.css' %}" />
        
        
        
        <title>LILAS</title>
    </head>
    <body>
        <header>
        <table style="width:100%;">
            <tr>
                <th> <h1>L I L A S</h1> </th>
                <th class="boutonApp" onclick="window.location.href='/incident'" style="border-bottom: 5px solid #d3defc;">Tickets d'événements</th> 
                <th class="boutonApp" onclick="window.location.href='/communication'">Tickets de communication</th>
                <th class="boutonApp" onclick="window.location.href='/configSalle'">Tickets opérateurs</th>
                <th class="boutonApp" onclick="window.location.href='/loadFic'"><img style="width: 30px; border-radius: 30px;" src="{% static 'loadFic/images/upload_icon.png' %}"></img></th>
            </tr>
        </table>
        </header>
        <div>
            <div>
                <form action="." method="post">
                    {% csrf_token %}
                    <ul>
                        <li>Date initiale {{ form.dateDebut }}</li>
                        <li>Heure initiale{{ form.heureDebut }}</li>
                        <li>Date de fin {{ form.dateFin }}</li>
                        <li>Heure de fin {{ form.heureFin }}</li>
                        <li><input type="submit" value="Submit"></li>
                    </ul>
                </form> 
            </div>
        </div>
        <div>
            <div class= "limiter">
                {% if IncidentListe %}
                <div>
                    <table id="tableauStatistiques">
                         <thead>
                            <tr>
                                <th class="colonne_type">Type élément</th>
                                <th class="colonne_nom">Nom élément</th>
                                <th class="colonne_etat">Etat élément</th>
                                <th class="colonne_gravite">Gravité</th>
                                <th class="colonne_apparition">Date d'apparition</th>
                                <th class="colonne_disparition">Date de disparition</th>                    
                            </tr>
                         </thead>
                         <tbody>
                            {% for incident in IncidentListe %}
                            <tr>
                                <td class="colonne_type">{{ incident.type_element }}</td>
                                <td class="colonne_nom">{{ incident.nom_element }}</td>
                                <td class="colonne_etat">{{ incident.etat_element }}</td>
                                <td class="colonne_gravite">{{ incident.gravite }}</td>
                                <td class="colonne_apparition">{{ incident.date_apparition|date:"d/m/y_H:i:s" }}</td>
                                <td class="colonne_disparition">{{ incident.date_disparition_systeme|date:"d/m/y_H:i:s" }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                     </table>
                 </div>
                 {% else %}
                <p>Aucun incident réperetorié.</p>
                {% endif %}   
            </div>
            
            <div class="limiter_stats">
            {% if listeStats %}
                
                <div>
                    <table id="tabStatF">
                        <thead>
                             <tr>
                                <th id = 'boutonNomElement' class="colonne1">Nom élément</th>
                                <th id = 'boutonNbOccurrence' class="colonne2">Nombre d'occurrences</th>
                                <th id = 'boutonDureeIndispo' class="colonne3">Durée d'indisponnibilité (s)</th>               
                            </tr>
                        </thead>
                        <tbody>
                            {% for s in listeStats %}
                            <tr>
                                <td class="colonne1">{{ s.0 }}</td>
                                <td class="colonne2">{{ s.1 }}</td>
                                <td class="colonne3">{{ s.2 }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                           
                {% endif %}
            </div>
        </div>
        <footer>
        </footer>
        <script id="TriLignesStat" type="text/javascript">
        
        let toggle = 0;
        
        
        //Fonctions de Tri
        function triParNomElementCroissant(a, b){
            var x = a[0];
            var y = b[0];
            return ((x < y) ? -1 : ((x > y) ? 1 : 0));
        }
        
        function triParNomElementDecroissant(a, b){
            var x = a[0];
            var y = b[0];
            return ((x > y) ? -1 : ((x < y) ? 1 : 0));
        }
        
        function triParNbOccurrenceCroissant(a, b){
            var x = Number(a[1]);
            var y = Number(b[1]);
            return ((x < y) ? -1 : ((x > y) ? 1 : 0));
        }
        
        function triParNboccurrenceDecroissant(a, b){
            var x = Number(a[1]);
            var y = Number(b[1]);
            return ((x > y) ? -1 : ((x < y) ? 1 : 0));
        }
        
        function triParDureeIndispoCroissant(a, b){
            var x = Number(a[2]);
            var y = Number(b[2]);
            return ((x < y) ? -1 : ((x > y) ? 1 : 0));
        }
        
        function triParDureeIndispoDecroissant(a, b){
            var x = Number(a[2]);
            var y = Number(b[2]);
            return ((x > y) ? -1 : ((x < y) ? 1 : 0));
        }
       
        
        //On récupère le tableau de statistiques dans un tableau javascript
        var tableau = document.getElementById("tabStatF").rows;
        var longueur = tableau.length;
        var tabStats = new Array();
        
        for (var i = 1; i < longueur; i++)
        {
            var ligne = tableau[i].cells;
            var tampon = new Array();
            for (var j = 0; j < 3; j++)  //ATTENTION !!! variable à changer si on augmente le nombre de colonnes du tableau de statistiques
            {
                tampon.push(ligne[j].innerHTML);
            }
            tabStats.push(tampon);
        }
            
        //tabStats est ici le tableau de statistiques. Il est rempli.
        
        //----- CLIQUE BOUTON NOM ELEMENT -----//
    
        const boutonNomElement = document.getElementById('boutonNomElement');
        boutonNomElement.addEventListener('click', function() {
    
            
        
            
            //On regarde à quelle valeur est le toggle
            
            if (toggle == 0)
            {
                //On trie les lignes de l'Array tabStats par ordre de durée Cumulée croissante.
                tabStats.sort(triParNomElementCroissant);
                toggle = 1;
            }
            else if (toggle == 1)
            {
                //On trie les lignes de l'Array tabStats par ordre de durée Cumulée croissante.
                tabStats.sort(triParNomElementDecroissant);
                toggle = 0;
            }
            
            
            
            //On remplace maintenant les lignes du tableau
            for (var i = 0; i < longueur-1; i++)
            {
                var ligne = tableau[i+1].cells;
                for (var j = 0; j < ligne.length; j++)
                {
                    ligne[j].innerHTML = tabStats[i][j];
                }
            }
        
        
        
        });
        
         //----- CLIQUE BOUTON NOMBRE OCCURRENCE -----//
    
        const boutonNbOccurrence = document.getElementById('boutonNbOccurrence');
        boutonNbOccurrence.addEventListener('click', function() {
            //On regarde à quelle valeur est le toggle
            
            if (toggle == 0)
            {
                //On trie les lignes de l'Array tabStats par ordre de durée Cumulée croissante.
                tabStats.sort(triParNbOccurrenceCroissant);
                toggle = 1;
            }
            else if (toggle == 1)
            {
                //On trie les lignes de l'Array tabStats par ordre de durée Cumulée croissante.
                tabStats.sort(triParNboccurrenceDecroissant);
                toggle = 0;
            }
            //On remplace maintenant les lignes du tableau
            
            for (var i = 0; i < longueur-1; i++)
            {
                var ligne = tableau[i+1].cells;
                for (var j = 0; j < ligne.length; j++)
                {
                    ligne[j].innerHTML = tabStats[i][j];
                }
            }

        });
        
         //----- CLIQUE BOUTON DUREE INDISPO -----//
    
        const boutonDureeIndispo = document.getElementById('boutonDureeIndispo');
        boutonDureeIndispo.addEventListener('click', function() {
            
            //On regarde à quelle valeur est le toggle
            
            if (toggle == 0)
            {
                //On trie les lignes de l'Array tabStats par ordre de durée Cumulée croissante.
                tabStats.sort(triParDureeIndispoCroissant);
                toggle = 1;
                
            }
            else if (toggle == 1)
            {
                //On trie les lignes de l'Array tabStats par ordre de durée Cumulée croissante.
                tabStats.sort(triParDureeIndispoDecroissant);
                toggle = 0;
            }
            
            
            
            //On remplace maintenant les lignes du tableau
            for (var i = 0; i < longueur-1; i++)
            {
                var ligne = tableau[i+1].cells;
                for (var j = 0; j < ligne.length; j++)
                {
                    ligne[j].innerHTML = tabStats[i][j];
                }
            }
        
        
        
        });
        
        </script>
        

<!-- NECESSAIRE A L'AFFICHAGE DU DATEPICKER -->
    <script src="{% static 'communication/lib_ext/datePicker_jquery-1.12.4.js' %}"></script>
    <script src="{% static 'communication/lib_ext/datePicker_jquery-ui.js' %}"></script>
    <script src="{% static 'communication/lib_ext/datePicker_jquery-ui.min.js' %}"></script>
<!-- NECESSAIRE A L'AFFICHAGE DU DATEPICKER -->
    

        <!-- NECESSAIRE A L'AFFICHAGE DU DATEPICKER -->
        <script>
           $(document).ready(function(){
             $('#id_dateDebut').datepicker({ dateFormat: 'dd/mm/yy',
            changeMonth: true,
            changeYear: true,
            showWeek: true,
            firstDay: 1,
            /*showOtherMonths: true,
            selectOtherMonths: true*/ });
            
            $('#id_dateFin').datepicker({ dateFormat: 'dd/mm/yy',
            changeMonth: true,
            changeYear: true,
            showWeek: true,
            firstDay: 1,
            /*showOtherMonths: true,
            selectOtherMonths: true*/ });
            });
        </script>
    
    
    </body>
    

</html>